### PR TITLE
SecretKey -> PublicKey preconditions docs + fixes.

### LINKED ISSUE #114: Insufficient private key validation (from nimbus-eth2)
Please see https://github.com/status-im/nimbus-eth2/issues/2693, not sure which repo was the best to report this issue, so created issue on both, hope it's ok.

### PR DESCRIPTION
**Pull request by mratsim**
This fixes #114 and https://github.com/status-im/nimbus-eth2/issues/2695

# Overview

In BLSCurve, preconditions checks for:
- SecretKey: 0 < SK < r (BLS12-381 curve order)
- PublicKey: PK != infinity and PK in G1 subgroup

are done at deserialization time.

https://github.com/status-im/nim-blscurve/blob/50dbaba38fbe451cf8620e433fe0fdffe2c215f0/blscurve/blst/bls_sig_io.nim#L149-L168
https://github.com/status-im/nim-blscurve/blob/50dbaba38fbe451cf8620e433fe0fdffe2c215f0/blscurve/blst/bls_sig_io.nim#L81-L99

This means that procedures that rely on those types, like `publicFromSecret` can assume that those preconditions are already respected.
This has been clarified in a dedicated document https://github.com/status-im/nim-blscurve/blob/9b7366cdc7df14c87930c3ed0243ab551a5daf56/docs/bls_types_guarantees.md

Tests have been added to ensure that #114 was just a documentation issue and revealed that the MIRACL backend (not used in production) could actually deserialize an invalid secret key > r.

Furthermore, for defensive programming reason, an extra precondition check in `publicFromSecret` has been added to recheck that the input respects `0 < SK < r`. That check should never fail.

### CODE REVIEW

File: blscurve/miracl/miracl_min_pubkey_sig_core.nim [hunk 1]
```diff
@@ -60,6 +60,10 @@ type
     ## Long-term storage of this key also requires adequate protection.
     ##
     ## At the moment, the nim-blscurve library does not guarantee such protections
+    ##
+    ## Guarantees:
+    ## - SecretKeys are always created (via hkdf_mod_r) or deserialized (via `fromBytes`)
```
Comment (arnetheduck) [inline blscurve/miracl/miracl_min_pubkey_sig_core.nim:65]: we can probably slap a `requiresInit` on it to catch any zero-initialized stragglers
